language: swift
osx_image: xcode9.2

install: true

before_install:
 - gem install cocoapods
 - pod --version
script:
 - pod repo update && pod update
 - set -o pipefail
 - xcodebuild -workspace RxFirebase.xcworkspace -scheme Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
 - travis_wait 30 pod lib lint RxFirebase.podspec
